networks:
  default:
    external:
      name: roboshop
services:
  mongodb:
    container_name: mongodb
    image: mongodb:1

  catalogue:
    container_name: catalogue
    image: catalogue:1
    depends_on:
      - mongodb
  
  web:
    container_name: web
    image: web:1
    depends_on:
      - catalogue

  redis:
    container_name: redis
    image: redis

  user:
    image: user:1
    container_name: user
    depends_on:
      - redis
      - mongodb

  cart:
    image: cart:1
    container_name: cart
    depends_on:
      - redis
      - catalogue